name: Add binder link to PR
on:
  pull_request:
    branches:
      - main

jobs:
  binder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/binder-link@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
